export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_PRODUCTS = "GET_PRODUCTS";

export const GET_PRODUCTS_BASKET = "GET_PRODUCTS_BASKET";
export const GET_BASKET_TOTAL_PRICE = "GET_BASKET_TOTAL_PRICE";
export const SET_BASKET_TOTAL_PRICE = "SET_BASKET_TOTAL_PRICE";
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REDUCE_FROM_BASKET = "REDUCE_FROM_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const CLEAR_BASKET = "CLEAR_BASKET";

export const GET_SHIPMENT_FEE = "GET_SHIPMENT_FEE";
export const SET_SHIPMENT_FEE = "SET_SHIPMENT_FEE";
export const GET_AMOUNT_TO_CHECKOUT = "GET_AMOUNT_TO_CHECKOUT";
export const SET_AMOUNT_TO_CHECKOUT = "SET_AMOUNT_TO_CHECKOUT";

export const STORAGEKEY = "ALPHASHOP_BASKET";

export const PAYMENTS_STEPS = ["address", "shipment", "method"];
export const SET_PAYMENTS_STEPS = "SET_PAYMENTS_STEPS";
export const GET_CURRENT_PAYMENTS_STEP = "CURRENT_PAYMENTS_STEP";
export const SET_CURRENT_PAYMENTS_STEP = "CURRENT_PAYMENTS_STEP";
export const GET_NEXT_PAYMENTS_STEP = "GET_NEXT_PAYMENTS_STEP";
export const SET_NEXT_PAYMENTS_STEP = "SET_NEXT_PAYMENTS_STEP";
export const GET_PREV_PAYMENTS_STEP = "GET_PREV_PAYMENTS_STEP";
export const SET_PREV_PAYMENTS_STEP = "SET_PREV_PAYMENTS_STEP";
export const CONFIRM_ORDER = "CONFIRM_ORDER";
export const SUBMIT_ORDER = "SUBMIT_ORDER";